// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/assimoes/beautix/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ClientLoyaltyService is an autogenerated mock type for the ClientLoyaltyService type
type ClientLoyaltyService struct {
	mock.Mock
}

// AddClientLoyaltyPoints provides a mock function with given fields: ctx, clientID, programID, pointsToAdd, updatedBy
func (_m *ClientLoyaltyService) AddClientLoyaltyPoints(ctx context.Context, clientID uuid.UUID, programID uuid.UUID, pointsToAdd int, updatedBy uuid.UUID) error {
	ret := _m.Called(ctx, clientID, programID, pointsToAdd, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for AddClientLoyaltyPoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, programID, pointsToAdd, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateClientLoyalty provides a mock function with given fields: ctx, clientID, programID, initialPoints
func (_m *ClientLoyaltyService) CreateClientLoyalty(ctx context.Context, clientID uuid.UUID, programID uuid.UUID, initialPoints int) (*domain.ClientLoyalty, error) {
	ret := _m.Called(ctx, clientID, programID, initialPoints)

	if len(ret) == 0 {
		panic("no return value specified for CreateClientLoyalty")
	}

	var r0 *domain.ClientLoyalty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) (*domain.ClientLoyalty, error)); ok {
		return rf(ctx, clientID, programID, initialPoints)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) *domain.ClientLoyalty); ok {
		r0 = rf(ctx, clientID, programID, initialPoints)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ClientLoyalty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r1 = rf(ctx, clientID, programID, initialPoints)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteClientLoyalty provides a mock function with given fields: ctx, clientID, programID, deletedBy
func (_m *ClientLoyaltyService) DeleteClientLoyalty(ctx context.Context, clientID uuid.UUID, programID uuid.UUID, deletedBy uuid.UUID) error {
	ret := _m.Called(ctx, clientID, programID, deletedBy)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClientLoyalty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, programID, deletedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClientLoyalty provides a mock function with given fields: ctx, clientID, programID
func (_m *ClientLoyaltyService) GetClientLoyalty(ctx context.Context, clientID uuid.UUID, programID uuid.UUID) (*domain.ClientLoyalty, error) {
	ret := _m.Called(ctx, clientID, programID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientLoyalty")
	}

	var r0 *domain.ClientLoyalty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.ClientLoyalty, error)); ok {
		return rf(ctx, clientID, programID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.ClientLoyalty); ok {
		r0 = rf(ctx, clientID, programID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ClientLoyalty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID, programID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListClientLoyalties provides a mock function with given fields: ctx, clientID
func (_m *ClientLoyaltyService) ListClientLoyalties(ctx context.Context, clientID uuid.UUID) ([]*domain.ClientLoyalty, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for ListClientLoyalties")
	}

	var r0 []*domain.ClientLoyalty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.ClientLoyalty, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.ClientLoyalty); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ClientLoyalty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListClientsByProgram provides a mock function with given fields: ctx, programID, page, pageSize
func (_m *ClientLoyaltyService) ListClientsByProgram(ctx context.Context, programID uuid.UUID, page int, pageSize int) ([]*domain.ClientLoyalty, error) {
	ret := _m.Called(ctx, programID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListClientsByProgram")
	}

	var r0 []*domain.ClientLoyalty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.ClientLoyalty, error)); ok {
		return rf(ctx, programID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.ClientLoyalty); ok {
		r0 = rf(ctx, programID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ClientLoyalty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, programID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedeemReward provides a mock function with given fields: ctx, clientID, programID, rewardID, updatedBy
func (_m *ClientLoyaltyService) RedeemReward(ctx context.Context, clientID uuid.UUID, programID uuid.UUID, rewardID uuid.UUID, updatedBy uuid.UUID) error {
	ret := _m.Called(ctx, clientID, programID, rewardID, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for RedeemReward")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, programID, rewardID, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateClientLoyaltyPoints provides a mock function with given fields: ctx, clientID, programID, points, updatedBy
func (_m *ClientLoyaltyService) UpdateClientLoyaltyPoints(ctx context.Context, clientID uuid.UUID, programID uuid.UUID, points int, updatedBy uuid.UUID) error {
	ret := _m.Called(ctx, clientID, programID, points, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClientLoyaltyPoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, programID, points, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClientLoyaltyService creates a new instance of ClientLoyaltyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientLoyaltyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientLoyaltyService {
	mock := &ClientLoyaltyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
