// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/assimoes/beautix/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// LoyaltyProgramService is an autogenerated mock type for the LoyaltyProgramService type
type LoyaltyProgramService struct {
	mock.Mock
}

// CountLoyaltyPrograms provides a mock function with given fields: ctx
func (_m *LoyaltyProgramService) CountLoyaltyPrograms(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountLoyaltyPrograms")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountLoyaltyProgramsByProvider provides a mock function with given fields: ctx, providerID
func (_m *LoyaltyProgramService) CountLoyaltyProgramsByProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for CountLoyaltyProgramsByProvider")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, providerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, providerID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, providerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLoyaltyProgram provides a mock function with given fields: ctx, input
func (_m *LoyaltyProgramService) CreateLoyaltyProgram(ctx context.Context, input *domain.CreateLoyaltyProgramInput) (*domain.LoyaltyProgram, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoyaltyProgram")
	}

	var r0 *domain.LoyaltyProgram
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateLoyaltyProgramInput) (*domain.LoyaltyProgram, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateLoyaltyProgramInput) *domain.LoyaltyProgram); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoyaltyProgram)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateLoyaltyProgramInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLoyaltyProgram provides a mock function with given fields: ctx, id, deletedBy
func (_m *LoyaltyProgramService) DeleteLoyaltyProgram(ctx context.Context, id uuid.UUID, deletedBy uuid.UUID) error {
	ret := _m.Called(ctx, id, deletedBy)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLoyaltyProgram")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, deletedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLoyaltyProgram provides a mock function with given fields: ctx, id
func (_m *LoyaltyProgramService) GetLoyaltyProgram(ctx context.Context, id uuid.UUID) (*domain.LoyaltyProgram, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLoyaltyProgram")
	}

	var r0 *domain.LoyaltyProgram
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.LoyaltyProgram, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.LoyaltyProgram); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoyaltyProgram)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLoyaltyProgramsByProvider provides a mock function with given fields: ctx, providerID, page, pageSize
func (_m *LoyaltyProgramService) ListLoyaltyProgramsByProvider(ctx context.Context, providerID uuid.UUID, page int, pageSize int) ([]*domain.LoyaltyProgram, error) {
	ret := _m.Called(ctx, providerID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListLoyaltyProgramsByProvider")
	}

	var r0 []*domain.LoyaltyProgram
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.LoyaltyProgram, error)); ok {
		return rf(ctx, providerID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.LoyaltyProgram); ok {
		r0 = rf(ctx, providerID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LoyaltyProgram)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, providerID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLoyaltyProgram provides a mock function with given fields: ctx, id, input, updatedBy
func (_m *LoyaltyProgramService) UpdateLoyaltyProgram(ctx context.Context, id uuid.UUID, input *domain.UpdateLoyaltyProgramInput, updatedBy uuid.UUID) error {
	ret := _m.Called(ctx, id, input, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLoyaltyProgram")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateLoyaltyProgramInput, uuid.UUID) error); ok {
		r0 = rf(ctx, id, input, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLoyaltyProgramService creates a new instance of LoyaltyProgramService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoyaltyProgramService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoyaltyProgramService {
	mock := &LoyaltyProgramService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
