// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/assimoes/beautix/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// NotificationSettingsService is an autogenerated mock type for the NotificationSettingsService type
type NotificationSettingsService struct {
	mock.Mock
}

// CreateNotificationSettings provides a mock function with given fields: ctx, input
func (_m *NotificationSettingsService) CreateNotificationSettings(ctx context.Context, input *domain.CreateNotificationSettingsInput) (*domain.NotificationSettings, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationSettings")
	}

	var r0 *domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateNotificationSettingsInput) (*domain.NotificationSettings, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateNotificationSettingsInput) *domain.NotificationSettings); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateNotificationSettingsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNotificationSettings provides a mock function with given fields: ctx, id
func (_m *NotificationSettingsService) DeleteNotificationSettings(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotificationSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBusinessNotificationSettings provides a mock function with given fields: ctx, businessID, notificationType
func (_m *NotificationSettingsService) GetBusinessNotificationSettings(ctx context.Context, businessID uuid.UUID, notificationType string) (*domain.NotificationSettings, error) {
	ret := _m.Called(ctx, businessID, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for GetBusinessNotificationSettings")
	}

	var r0 *domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.NotificationSettings, error)); ok {
		return rf(ctx, businessID, notificationType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.NotificationSettings); ok {
		r0 = rf(ctx, businessID, notificationType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, businessID, notificationType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotificationSettings provides a mock function with given fields: ctx, id
func (_m *NotificationSettingsService) GetNotificationSettings(ctx context.Context, id uuid.UUID) (*domain.NotificationSettings, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationSettings")
	}

	var r0 *domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.NotificationSettings, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.NotificationSettings); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBusinessNotificationSettings provides a mock function with given fields: ctx, businessID
func (_m *NotificationSettingsService) ListBusinessNotificationSettings(ctx context.Context, businessID uuid.UUID) ([]*domain.NotificationSettings, error) {
	ret := _m.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for ListBusinessNotificationSettings")
	}

	var r0 []*domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.NotificationSettings, error)); ok {
		return rf(ctx, businessID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.NotificationSettings); ok {
		r0 = rf(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotificationSettings provides a mock function with given fields: ctx, id, input
func (_m *NotificationSettingsService) UpdateNotificationSettings(ctx context.Context, id uuid.UUID, input *domain.UpdateNotificationSettingsInput) error {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateNotificationSettingsInput) error); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationSettingsService creates a new instance of NotificationSettingsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationSettingsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationSettingsService {
	mock := &NotificationSettingsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
