// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/assimoes/beautix/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// NotificationSettingsRepository is an autogenerated mock type for the NotificationSettingsRepository type
type NotificationSettingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, settings
func (_m *NotificationSettingsRepository) Create(ctx context.Context, settings *domain.NotificationSettings) error {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NotificationSettings) error); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *NotificationSettingsRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByBusinessAndType provides a mock function with given fields: ctx, businessID, notificationType
func (_m *NotificationSettingsRepository) GetByBusinessAndType(ctx context.Context, businessID uuid.UUID, notificationType string) (*domain.NotificationSettings, error) {
	ret := _m.Called(ctx, businessID, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for GetByBusinessAndType")
	}

	var r0 *domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.NotificationSettings, error)); ok {
		return rf(ctx, businessID, notificationType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.NotificationSettings); ok {
		r0 = rf(ctx, businessID, notificationType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, businessID, notificationType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *NotificationSettingsRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.NotificationSettings, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.NotificationSettings, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.NotificationSettings); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByBusiness provides a mock function with given fields: ctx, businessID
func (_m *NotificationSettingsRepository) ListByBusiness(ctx context.Context, businessID uuid.UUID) ([]*domain.NotificationSettings, error) {
	ret := _m.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for ListByBusiness")
	}

	var r0 []*domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.NotificationSettings, error)); ok {
		return rf(ctx, businessID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.NotificationSettings); ok {
		r0 = rf(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, input
func (_m *NotificationSettingsRepository) Update(ctx context.Context, id uuid.UUID, input *domain.UpdateNotificationSettingsInput) error {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateNotificationSettingsInput) error); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationSettingsRepository creates a new instance of NotificationSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationSettingsRepository {
	mock := &NotificationSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
