// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/assimoes/beautix/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PermissionScopeRepository is an autogenerated mock type for the PermissionScopeRepository type
type PermissionScopeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, scope
func (_m *PermissionScopeRepository) Create(ctx context.Context, scope *domain.PermissionScope) error {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PermissionScope) error); ok {
		r0 = rf(ctx, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PermissionScopeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByUserAndBusiness provides a mock function with given fields: ctx, userID, businessID
func (_m *PermissionScopeRepository) DeleteByUserAndBusiness(ctx context.Context, userID uuid.UUID, businessID uuid.UUID) error {
	ret := _m.Called(ctx, userID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserAndBusiness")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, businessID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserAndBusiness provides a mock function with given fields: ctx, userID, businessID
func (_m *PermissionScopeRepository) GetByUserAndBusiness(ctx context.Context, userID uuid.UUID, businessID uuid.UUID) ([]*domain.PermissionScope, error) {
	ret := _m.Called(ctx, userID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndBusiness")
	}

	var r0 []*domain.PermissionScope
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.PermissionScope, error)); ok {
		return rf(ctx, userID, businessID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*domain.PermissionScope); ok {
		r0 = rf(ctx, userID, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PermissionScope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, businessID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPermissionScopeRepository creates a new instance of PermissionScopeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionScopeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionScopeRepository {
	mock := &PermissionScopeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
