// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/assimoes/beautix/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ServiceAssignmentRepository is an autogenerated mock type for the ServiceAssignmentRepository type
type ServiceAssignmentRepository struct {
	mock.Mock
}

// CountByBusiness provides a mock function with given fields: ctx, businessID
func (_m *ServiceAssignmentRepository) CountByBusiness(ctx context.Context, businessID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for CountByBusiness")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, businessID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, businessID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, assignment
func (_m *ServiceAssignmentRepository) Create(ctx context.Context, assignment *domain.ServiceAssignment) error {
	ret := _m.Called(ctx, assignment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ServiceAssignment) error); ok {
		r0 = rf(ctx, assignment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, deletedBy
func (_m *ServiceAssignmentRepository) Delete(ctx context.Context, id uuid.UUID, deletedBy uuid.UUID) error {
	ret := _m.Called(ctx, id, deletedBy)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, deletedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ServiceAssignmentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.ServiceAssignment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.ServiceAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ServiceAssignment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ServiceAssignment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ServiceAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByService provides a mock function with given fields: ctx, serviceID
func (_m *ServiceAssignmentRepository) GetByService(ctx context.Context, serviceID uuid.UUID) ([]*domain.ServiceAssignment, error) {
	ret := _m.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByService")
	}

	var r0 []*domain.ServiceAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.ServiceAssignment, error)); ok {
		return rf(ctx, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.ServiceAssignment); ok {
		r0 = rf(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ServiceAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByStaff provides a mock function with given fields: ctx, staffID
func (_m *ServiceAssignmentRepository) GetByStaff(ctx context.Context, staffID uuid.UUID) ([]*domain.ServiceAssignment, error) {
	ret := _m.Called(ctx, staffID)

	if len(ret) == 0 {
		panic("no return value specified for GetByStaff")
	}

	var r0 []*domain.ServiceAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.ServiceAssignment, error)); ok {
		return rf(ctx, staffID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.ServiceAssignment); ok {
		r0 = rf(ctx, staffID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ServiceAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, staffID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByStaffAndService provides a mock function with given fields: ctx, staffID, serviceID
func (_m *ServiceAssignmentRepository) GetByStaffAndService(ctx context.Context, staffID uuid.UUID, serviceID uuid.UUID) (*domain.ServiceAssignment, error) {
	ret := _m.Called(ctx, staffID, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByStaffAndService")
	}

	var r0 *domain.ServiceAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.ServiceAssignment, error)); ok {
		return rf(ctx, staffID, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.ServiceAssignment); ok {
		r0 = rf(ctx, staffID, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ServiceAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, staffID, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByBusiness provides a mock function with given fields: ctx, businessID, page, pageSize
func (_m *ServiceAssignmentRepository) ListByBusiness(ctx context.Context, businessID uuid.UUID, page int, pageSize int) ([]*domain.ServiceAssignment, error) {
	ret := _m.Called(ctx, businessID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListByBusiness")
	}

	var r0 []*domain.ServiceAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.ServiceAssignment, error)); ok {
		return rf(ctx, businessID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.ServiceAssignment); ok {
		r0 = rf(ctx, businessID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ServiceAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, businessID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, input, updatedBy
func (_m *ServiceAssignmentRepository) Update(ctx context.Context, id uuid.UUID, input *domain.UpdateServiceAssignmentInput, updatedBy uuid.UUID) error {
	ret := _m.Called(ctx, id, input, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateServiceAssignmentInput, uuid.UUID) error); ok {
		r0 = rf(ctx, id, input, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceAssignmentRepository creates a new instance of ServiceAssignmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAssignmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAssignmentRepository {
	mock := &ServiceAssignmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
