// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/assimoes/beautix/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// ServiceCompletionRepository is an autogenerated mock type for the ServiceCompletionRepository type
type ServiceCompletionRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *ServiceCompletionRepository) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByProvider provides a mock function with given fields: ctx, providerID
func (_m *ServiceCompletionRepository) CountByProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for CountByProvider")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, providerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, providerID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, providerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, completion
func (_m *ServiceCompletionRepository) Create(ctx context.Context, completion *domain.ServiceCompletion) error {
	ret := _m.Called(ctx, completion)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ServiceCompletion) error); ok {
		r0 = rf(ctx, completion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, deletedBy
func (_m *ServiceCompletionRepository) Delete(ctx context.Context, id uuid.UUID, deletedBy uuid.UUID) error {
	ret := _m.Called(ctx, id, deletedBy)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, deletedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAppointmentID provides a mock function with given fields: ctx, appointmentID
func (_m *ServiceCompletionRepository) GetByAppointmentID(ctx context.Context, appointmentID uuid.UUID) (*domain.ServiceCompletion, error) {
	ret := _m.Called(ctx, appointmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAppointmentID")
	}

	var r0 *domain.ServiceCompletion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ServiceCompletion, error)); ok {
		return rf(ctx, appointmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ServiceCompletion); ok {
		r0 = rf(ctx, appointmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ServiceCompletion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, appointmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ServiceCompletionRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.ServiceCompletion, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.ServiceCompletion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ServiceCompletion, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ServiceCompletion); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ServiceCompletion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProviderRevenue provides a mock function with given fields: ctx, providerID, startDate, endDate
func (_m *ServiceCompletionRepository) GetProviderRevenue(ctx context.Context, providerID uuid.UUID, startDate time.Time, endDate time.Time) (float64, error) {
	ret := _m.Called(ctx, providerID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderRevenue")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) (float64, error)); ok {
		return rf(ctx, providerID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, providerID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, providerID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByProvider provides a mock function with given fields: ctx, providerID, startDate, endDate, page, pageSize
func (_m *ServiceCompletionRepository) ListByProvider(ctx context.Context, providerID uuid.UUID, startDate time.Time, endDate time.Time, page int, pageSize int) ([]*domain.ServiceCompletion, error) {
	ret := _m.Called(ctx, providerID, startDate, endDate, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListByProvider")
	}

	var r0 []*domain.ServiceCompletion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, int, int) ([]*domain.ServiceCompletion, error)); ok {
		return rf(ctx, providerID, startDate, endDate, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, int, int) []*domain.ServiceCompletion); ok {
		r0 = rf(ctx, providerID, startDate, endDate, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ServiceCompletion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time, int, int) error); ok {
		r1 = rf(ctx, providerID, startDate, endDate, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, input, updatedBy
func (_m *ServiceCompletionRepository) Update(ctx context.Context, id uuid.UUID, input *domain.UpdateServiceCompletionInput, updatedBy uuid.UUID) error {
	ret := _m.Called(ctx, id, input, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateServiceCompletionInput, uuid.UUID) error); ok {
		r0 = rf(ctx, id, input, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceCompletionRepository creates a new instance of ServiceCompletionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceCompletionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceCompletionRepository {
	mock := &ServiceCompletionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
