version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: beautix_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beautix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Uncomment this service when you need pgAdmin
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: beautix_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@beautix.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
    driver: local